# Site settings
title: Dennis Waldherr
email: therealdante@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Games, Hardware and Code
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://Bytekeeper.github.io.git" # the base hostname & protocol for your site
twitter_username: Bytekeeper
github_username:  Bytekeeper

# Build settings
markdown: kramdown

collections:
  sidebar:
  cats:
    output: true

